import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RUNTIME_PATH = path.join(__dirname, 'runtime', 'builder.js');

function header(source) {
  return [
    '// Generated by html-to-figma',
    `// Source: ${source}`,
    '// Run this in Figma via the Scripter plugin, or import the generated',
    '// plugin folder (Plugins → Development → Import plugin from manifest).',
    '',
  ].join('\n');
}

/**
 * Produce a self-contained Figma Plugin API script from an extracted tree.
 * @param {object} tree - tree from extractTree()
 * @param {object} [opts]
 * @param {string} [opts.source] - label for the header comment
 * @param {boolean} [opts.closePlugin] - append figma.closePlugin() on finish (for plugin code.js)
 */
export function generateScript(tree, opts = {}) {
  const runtime = fs.readFileSync(RUNTIME_PATH, 'utf8');
  const close = opts.closePlugin ? 'true' : 'false';
  return [
    header(opts.source || 'html'),
    `const __TREE__ = ${JSON.stringify(tree)};`,
    '',
    runtime,
    '',
    `main(__TREE__, { close: ${close} }).catch((err) => {`,
    "  console.error('html-to-figma:', err);",
    "  figma.notify('html-to-figma failed: ' + err.message, { error: true });",
    ...(opts.closePlugin ? ['  figma.closePlugin();'] : []),
    '});',
    '',
  ].join('\n');
}

/** Write the Scripter script, a ready-to-import plugin folder, and the debug tree. */
export function writeOutputs(tree, outDir, opts = {}) {
  fs.mkdirSync(outDir, { recursive: true });
  const written = [];

  const scriptPath = path.join(outDir, 'figma-script.js');
  fs.writeFileSync(scriptPath, generateScript(tree, { source: opts.source, closePlugin: false }));
  written.push(scriptPath);

  if (opts.plugin !== false) {
    const pluginDir = path.join(outDir, 'figma-plugin');
    fs.mkdirSync(pluginDir, { recursive: true });
    const manifest = {
      name: opts.pluginName || 'html-to-figma import',
      id: 'com.html-to-figma.generated',
      api: '1.0.0',
      main: 'code.js',
      editorType: ['figma'],
    };
    const manifestPath = path.join(pluginDir, 'manifest.json');
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
    const codePath = path.join(pluginDir, 'code.js');
    fs.writeFileSync(codePath, generateScript(tree, { source: opts.source, closePlugin: true }));
    written.push(manifestPath, codePath);
  }

  if (opts.debugTree !== false) {
    const treePath = path.join(outDir, 'tree.json');
    fs.writeFileSync(treePath, JSON.stringify(tree, null, 2));
    written.push(treePath);
  }

  return written;
}
